### ISSUE TITLE
doubt

### ISSUE THREAD

**Issue by yeahhhhhhhhhhhhhhhhh** [overstatement/hCaptcha-Bypass#1]
where do you get accessibility?

**Comment by overstatement** [comment]
https://www.hcaptcha.com/accessibility

**Comment by overstatement** [comment]
look at the code, if you don't know python then don't use this

**Comment by yeahhhhhhhhhhhhhhhhh** [comment]
> https://www.hcaptcha.com/accessibility

right this i know, but the code i need to get to put in your code how do i get it?

**Comment by overstatement** [comment]
> > https://www.hcaptcha.com/accessibility
> 
> right this i know, but the code i need to get to put in your code how do i get it?

Read the readme
